#Numpy

In [1]:

my_list=[1,2,3,4]
my_list=my_list*2
print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


when we directly multiply list by 2 it just duplicate the list so to make computation simpler we use numpy

In [2]:
import numpy as np
array=np.array([1,2,3,4])
print(array)
array=array * 2
print(array)

print(type(array))  #nd=N-dimensional


[1 2 3 4]
[2 4 6 8]
<class 'numpy.ndarray'>


#multidimensional array

In [3]:
import numpy as np
arr=np.array(45)
print(arr.ndim)

array= np.array(['A'])
print(array.ndim)

two_d_array=np.array([[1,2,3],[4,5,6]])
print(two_d_array.ndim)

three_d_array=np.array([ [['A','B'],['C','D'],['U','T']],
                        [['G','I'],['E','F'],['Y','Z']] ])
print(three_d_array.ndim)
print(three_d_array.shape)



0
1
2
3
(2, 3, 2)


#multidimensional indexing

faster than chain indexing

chain indexing: array[1][0]

In [4]:
import numpy as np
three_d_array=np.array([ [['A','B'],['C','D'],['U','T']],
                        [['G','I'],['E','F'],['Y','Z']] ])
#CHAIN INDEXING
print(three_d_array[1][1][0])
print(three_d_array[1][2][0])
print(three_d_array[1][2][1])

#comma indexing OR multidimensional indexing
print(three_d_array[1,1,0])

#print ACID thrugh comma indexing
word= three_d_array[0,0,0]+ three_d_array[0,1,0]+ three_d_array[1,0,1]+ three_d_array[0,1,1]
print(word)



E
Y
Z
E
ACID


#SLICING

In [5]:
#row selection
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,16,16]])
#array[start:end:step]
print(arr[0:4])
print(arr[1:3])
print(arr[::-1])
print(arr[0:4:2])
print(arr[::-2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 16 16]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 16 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 16 16]
 [ 5  6  7  8]]


In [6]:
#column selection
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
#array[start:end:step]

print(arr[:,2])

print(arr[:,0:3])
print(arr[:,::2])

print(arr[1,1:3])
print(arr[2,0:])
print(arr[1,0:4:2])



[ 3  7 11 15]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[6 7]
[ 9 10 11 12]
[5 7]


#arithmetic

In [7]:
#scalar arithmetic

import numpy as np
array=np.array([1,2,3,4,5])
print(array+1)
print(array-2)
print(array*3)
print(array/2)
print(array**5)

[2 3 4 5 6]
[-1  0  1  2  3]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]
[   1   32  243 1024 3125]


In [8]:
#vectorized math funcs
radii=np.array([1,2,3])
print(np.pi* radii**2)


[ 3.14159265 12.56637061 28.27433388]


In [9]:
#element wise arithmetic

array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print(array1**array2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [10]:
#comparison operators
scores=np.array([56,89,67,78,99])
print(scores == 100)
print( scores>=80)
print(scores<50)
scores[scores<60]=0
print(scores)


[False False False False False]
[False  True False False  True]
[False False False False False]
[ 0 89 67 78 99]


#Broadcasting

allows NumPy to perform operations on array with different shapes by virtually expanding dimensions so they match the larger arry's shape

#Rules
-the dimensions have the same size                                    OR  
-one of the dimensions has size of 1

In [11]:
array1=np.array([[1,2,3,4]])
array2=np.array([[5],[6],[7],[8]])
print(array1.shape)
print(array2.shape)
#right to left
print(array1*array2)
print((array1 * array2).shape)



(1, 4)
(4, 1)
[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]
(4, 4)


In [12]:
array1=np.array([[1,2,3,4,5,6,7,8,9,10]])
array2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1.shape)
print(array2.shape)
print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


#Aggregate functions
summarize data and typically return single value

In [13]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))

print(np.sum(array,axis=0)) #axis=0 :column ;axis=1:row



55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]


#Filtering

refers to the process of selecting elements from an array that match the given condition

In [14]:
ages= np.array([[24,17,19,30,16,30,65],[34,56,22,15,30,18,19]])
teenager=ages[ages<18]
print(teenager)
adults=ages[(ages>=18) & (ages<65)]
adult=ages[(ages>18)| (ages <65)]
print(adults)

even=ages[ages%2==0]
print(even)

#preserve original shape of array
adultss= np.where(ages>=18,ages, 0) #fillvalue if not match condition to 0
print(adultss)


[17 16 15]
[24 19 30 30 34 56 22 30 18 19]
[24 30 16 30 34 56 22 30 18]
[[24  0 19 30  0 30 65]
 [34 56 22  0 30 18 19]]


#Random numbers

useful for simulation, modeling etc


In [15]:
import numpy as np
rng=np.random.default_rng()
print(rng.integers(1,7))
print(rng.integers(low=1,high=101,size=3)) #1D
print(rng.integers(low=1,high=101,size=(3,2))) #2D

print(np.random.uniform()) #floating point number


4
[ 3 28 91]
[[ 9 17]
 [ 1 80]
 [ 1 88]]
0.6501497236677837


In [16]:
rng=np.random.default_rng()
fruits=np.array(['apple','banana','mango','kiwi','pineapple'])
fruit=rng.choice(fruits,size=2)
print(fruit)

['banana' 'apple']
